# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 05:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Employee Firstname', max_length=50)),
                ('lastname', models.CharField(help_text='Employee Lastname', max_length=50)),
                ('salary', models.CharField(help_text='Weekly Income of Employee', max_length=9)),
                ('position', models.CharField(help_text='Job Position', max_length=35)),
                ('hours_worked', models.IntegerField(default=0, help_text='Weekly Hours', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Restaurant Name', max_length=75)),
                ('address', models.CharField(help_text='Location', max_length=125)),
                ('theme', models.CharField(help_text='Theme of Restaurant', max_length=50)),
                ('description', models.TextField(help_text='Information About Restaurant')),
            ],
        ),
    ]
