# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(help_text='Weekly Income of Employee', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(help_text='Information About Restaurant', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(help_text='Theme of Restaurant', max_length=50, null=True),
        ),
    ]
