# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0002_auto_20180506_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(default=None, help_text='Weekly Income of Employee', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=None, help_text='Information About Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(default=None, help_text='Theme of Restaurant', max_length=50),
            preserve_default=False,
        ),
    ]
