# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0003_auto_20180506_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 6, 16, 45, 1, 325694), help_text='Employee Start Date'),
        ),
    ]
