# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0004_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Employee Start Date'),
        ),
    ]
