# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0005_auto_20180506_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(help_text='Weekly Income of Employee', max_length=9),
        ),
    ]
