# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0007_auto_20180514_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_firstname', models.CharField(max_length=75)),
                ('customer_lastname', models.CharField(max_length=75)),
                ('customer_age', models.IntegerField(help_text='Age of Customer')),
                ('customer_gender', models.CharField(help_text='Male/Female/Other', max_length=6)),
                ('rental_plan', models.CharField(help_text='Weekly/Monthly/Yearly', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPlan',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_payment', models.CharField(help_text='Weekly/Monthly/Yearly', max_length=7)),
                ('has_paid', models.CharField(help_text='Yes/No/Extended', max_length=8)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_file.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('drivetrain', models.CharField(max_length=50)),
                ('passenger_capacity', models.IntegerField(help_text='How Many Seatable Passengers')),
                ('vehicle_type', models.CharField(help_text='Offroad/Truck/Lightweight etc', max_length=50)),
                ('vehicle_description', models.TextField(help_text="Description about Vehicle's Condition")),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_file.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_file.Vehicle'),
        ),
    ]
