# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 06:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0008_auto_20180514_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_age',
            field=models.IntegerField(help_text='Must be above 18 to Register', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='passenger_capacity',
            field=models.IntegerField(help_text='How Many Seatable Passengers', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
