# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0009_auto_20180514_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(help_text='FWD/RWD/AWD/2WD/4WD', max_length=50),
        ),
    ]
