# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0015_auto_20180514_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalplan',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='RentalPlan',
        ),
    ]
