# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0016_auto_20180514_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='type',
        ),
    ]
