# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0017_auto_20180514_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.IntegerField(default='012345678', help_text='Personal/Company'),
        ),
    ]
