# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 08:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0018_customer_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Up to 8 Digits', regex='^(\\d{1,9})/?')]),
        ),
    ]
