# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 08:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0020_auto_20180514_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Up to 12 Digits', regex='^(\\d{1,9})/?')]),
        ),
    ]
