# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0021_auto_20180514_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default=2002, help_text='Year when Vehicle was Produced', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(help_text='Offroad/Truck/Lightweight/Family Car etc', max_length=50),
        ),
    ]
