# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_file', '0022_auto_20180514_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text="Description about Vehicle's Condition"),
        ),
    ]
